### ISSUE TITLE
ShortcutBar

### ISSUE THREAD

**Issue by Timorem** [Emudofus/BehaviorIsManaged#28]
Does not work properly. No updates at all.

**Comment by FastFrench** [comment]
I wonder if the problem is not simply that you get SpellShortcuts.Get(1) instead of looking for the right slot within all ShortCuts. They are not sorted. 
The ShortcutBarContentMessage do not provide them sorted by Slot range. 
I've not tested, but if you write SpellShortcuts.Shortcuts.FirstOrDefault(sc => sc.Slot == 1) instead, it may do the trick.

**Comment by Timorem** [comment]
``` csharp
        public T Get(int slot)
        {
            return Shortcuts.FirstOrDefault(x => x.Slot == slot);
        }
```

;)
