### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by DjTrilogic** [Emudofus/BehaviorIsManaged#62]
I miss u guys, i hope u didn't leave that wonderful project ... where are youuuu ?

**Comment by vendethiel** [comment]
working on stump. and revising

**Comment by FastFrench** [comment]
Nope, project is dead :( 
RIP

Was a good one.

**Comment by vendethiel** [comment]
yeah, well, bouh2's gonna be busy for 2 years+ now :3

**Comment by Timorem** [comment]
Yeah i definitely won't have the motivation and the time to keep it alive

**Comment by codexedoc** [comment]
Hi guys, I'm veey interested by this beautiful piece of work and I'd like to contact somebody on the team.

**Comment by FastFrench** [comment]
I'm afraid it's a bit dead now here....

**Comment by codexedoc** [comment]
too bad, I was gonna make my own bot using some of your code.

**Comment by vendethiel** [comment]
what's wrong with that/forking/contributing back, though ?

**Comment by yelhouti** [comment]
Hi guys I'm also interested in taking back the project, I just need some of your help, I've cloned the project and started working on it, I've managed to understand a part of it, but I'm still not able to make it work, also I couldn't run the protocol builder to add the new classes (I had to do it manually) since I don't have the source code of Dofus, can you tell me what did you use to get it.
Also the only way I could make the the application create a bot with a proper socket is by using a proxy that redirects the traffic to localhost, was it a bad idea? how do I need to proceed plz to the the MITM.
Thanks for your answers.
Bests
